tickers:
  - BBCA.JK
  - BBRI.JK
start_date: "2021-09-03"
end_date: "2026-09-03"
train_size_ratio: 0.8
target_col: "close"
random_state: 42

# Hyperparameter Deep Learning
window_size: 30
batch_size: 32
epochs: 50
learning_rate: 0.001
