TICKERS:
  - BBCA.JK
  - BBRI.JK
START_DATE: "2025-09-03"
END_DATE: "2026-09-03"

TARGET_COL: "close"
RANDOM_STATE: 42
TRAIN_SIZE: 0.9
EPOCHS: 50

# Hyperparameter
TIME_STEPS:
  - 10
  - 20
  - 30
OPTIMIZERS:
  - SGD
  - Adam
  - RMSprop
BATCH_SIZES:
  - 8
  - 16
  - 32
LEARNING_RATES:
  - 0.01
  - 0.001
  - 0.0001
