TICKERS:
  - BBCA.JK
RANGE_DAYS: 1825
END_DATE: "auto"

TARGET_COL: "close"
RANDOM_STATE: 42
TRAIN_SIZE: 0.9
EPOCHS: 50

# Hyperparameter
TIME_STEPS:
  - 10
OPTIMIZERS:
  - Adam
BATCH_SIZES:
  - 8
LEARNING_RATES:
  - 0.01
