[project]
name = "mlops-stock-forecasting"
version = "0.1.0"
description = "MLOps Pipeline for Stock Forecasting"
readme = "README.md"
authors = [{ name = "Nashrullah Fathul Qoriib", email = "nashrullah.122140162@student.itera.ac.id" }]

requires-python = ">=3.10"
dependencies = [
  "dvc>=3.50.0",
  "dvc-s3>=3.0.0",
  "ipykernel>=6.29.0",
  "matplotlib>=3.8.0",
  "mlflow>=3.0.0",
  "numpy>=1.26.0",
  "pandas>=2.2.0",
  "papermill>=2.5.0",
  "python-dotenv>=1.0.0",
  "pyyaml>=6.0.1",
  "scikit-learn>=1.4.0",
  "seaborn>=0.13.0",
  "tensorflow==2.19.1",
  "tqdm>=4.66.0",
  "yfinance>=0.2.30",
  "nbconvert (>=7.17.1,<8.0.0)",
]

[project.scripts]
ingestion = "src.ingestion:main"
store = "src.store:main"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
packages = [{ include = "src" }]
