name: 'Setup Pipeline'
description: 'Sets up Python, Poetry, installs dependencies, and pulls data.'
inputs:
  python-version:
    description: 'Python version'
    required: false
    default: '3.12'
runs:
  using: 'composite'
  steps:
    - name: Configure Git Bot
      shell: bash
      env:
        GIT_USER_NAME: "github-actions[bot]"
        GIT_USER_EMAIL: "github-actions[bot]@users.noreply.github.com"
      run: |
        git config --global user.name "$GIT_USER_NAME"
        git config --global user.email "$GIT_USER_EMAIL"

    - name: Setup Python
      uses: actions/setup-python@v7
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest

    - name: Install Dependencies (Local Cache)
      shell: bash
      run: poetry install --no-interaction

    - name: DVC Pull
      shell: bash
      run: poetry run dvc pull --run-cache
